name: Run Tests

on: [push]

jobs:
  vm-job:
    name: Run Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" -- v1.3.3

      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Integration Test ZeedzINO
        run: flow test --cover ./cadence/tests/**/**/**.t.cdc
